alias ls='ls -F --color=always'
alias dir='dir -F --color=always'
alias ll='ls -lah'
alias cp='cp -iv'
alias rm='rm -i'
alias mv='mv -iv'
alias grep='grep --color=auto -in'
alias hist='log --color --pretty=format:\"%C(yellow)%h%C(reset) %s%C(bold red)%d%C(reset) %C(green)%ad%C(reset) %C(blue)[%an]%C(reset)\" --relative-date --decorate'
alias tmux='tmux -2'
alias php='php -dzend_extension="/usr/lib64/php/modules/xdebug.so"'
alias cmd-debug='export XDEBUG_CONFIG="idekey=PHPStorm"'
alias cmd-debug-off='export XDEBUG_CONFIG=""'
alias asd='app/console'
